import React, { useRef } from "react";
import { scrollToFinal, useCertReveal } from "./hooks";

function HypothesisCard() {
  return (
    <div className="prod-card glow">
      <div className="pc-header">
        <span className="pc-h-title">Research Hypothesis</span>
        <span className="pc-live">Live</span>
      </div>
      <div className="pc-body">
        <div className="pc-row"><span className="pc-key">Market</span><span className="pc-val">French pharmacy skincare — indie & challenger brands</span></div>
        <div className="pc-row"><span className="pc-key">Question</span><span className="pc-val">How are indie brands gaining shelf space and building social presence?</span></div>
        <div className="pc-row"><span className="pc-key">Tracking</span><span className="pc-val">Typology · Novexpert · La Roche-Posay · Caudalie</span></div>
        <div className="pc-row"><span className="pc-key">Geography</span><span className="pc-val">France · French-speaking Belgium</span></div>
      </div>
      <div className="pc-footer">
        <button className="pc-confirm">Confirm hypothesis &nbsp;→</button>
      </div>
    </div>
  );
}

function SignalFeedCard() {
  const entries = [
    { src: "Maddyness", time: "2 hours ago", text: "Typology lance une gamme professionnelle en exclusivité pharmacie...", chip: "Product Launch", chipClass: "c-launch" },
    { src: "EU Parliament", time: "6 hours ago", text: "New cosmetic ingredient regulation enters enforcement phase across member states...", chip: "Regulatory", chipClass: "c-reg" },
    { src: "FrenchWeb", time: "1 day ago", text: "Novexpert lève 4M€ en Serie A pour accélérer son déploiement retail...", chip: "Funding", chipClass: "c-fund" },
  ];
  return (
    <div className="sig-card">
      <div className="sig-card-scan" />
      <div className="sig-top-bar">
        <span className="pc-h-title">Live Signal Feed</span>
        <span className="sig-new-badge">3 new</span>
      </div>
      {entries.map((e) => (
        <div className="sig-entry" key={e.src}>
          <div className="sig-e-top">
            <span className="sig-src">{e.src}</span>
            <span className="sig-time">{e.time}</span>
          </div>
          <div className="sig-txt">{e.text}</div>
          <span className={`sig-chip ${e.chipClass}`}>{e.chip}</span>
        </div>
      ))}
    </div>
  );
}

function CertificateCard({ certCardRef }) {
  const lines = [
    ["Sources", "23 distinct sources", true],
    ["Date range", "01 Mar – 31 Mar 2026", false],
    ["Total signals", "847 retrieved", true],
    ["Deduplication", "Cosine similarity > 0.92", false],
    ["High confidence", "10+ signals, 5+ sources", false],
    ["Low confidence", "<3 signals — flagged", false],
    ["Language", "French", false],
  ];
  return (
    <div className="cert-card2" id="cert-card2" ref={certCardRef}>
      <div className="cert2-hd">
        <div>
          <div className="cert2-tag">Methodology Certificate</div>
          <div className="cert2-name">French Skincare Indie<br />Market Brief — Q1 2026</div>
        </div>
        <span className="cert2-badge">● Verified</span>
      </div>
      <div className="cert2-lines" id="cert2-lines">
        {lines.map(([k, v, green]) => (
          <div className="cert2-line" key={k}>
            <span className="cert2-k">{k}</span>
            <span className={`cert2-v ${green ? "g" : ""}`}>{v}</span>
          </div>
        ))}
      </div>
      <div className="cert2-foot">Generated by PulseLoop · pulseloop.io</div>
    </div>
  );
}

function FeatureSection({ id, flip, tag, heading, body, visual }) {
  return (
    <section className="feat-section" id={id}>
      <div className="section-wrap">
        <div className={`feat-grid ${flip ? "flip" : ""}`}>
          <div className="feat-copy">
            <div className="feat-tag">{tag}</div>
            <h2 className="feat-h">{heading}</h2>
            <p className="feat-body">{body}</p>
            <button className="feat-link" onClick={scrollToFinal}>Join the waitlist →</button>
          </div>
          <div>{visual}</div>
        </div>
      </div>
    </section>
  );
}

export default function Features() {
  const certCardRef = useRef(null);
  useCertReveal(certCardRef);

  return (
    <>
      <FeatureSection
        id="f1"
        tag="The Hypothesis"
        heading="You paste the brief. We build the research plan."
        body="Paste your client brief — or answer 3 questions. PulseLoop reads it, identifies what to track, and confirms a research hypothesis with you before running a single search."
        visual={<HypothesisCard />}
      />
      <FeatureSection
        id="f2"
        flip
        tag="The Intelligence"
        heading="Signals from 100+ EU sources. Not generic web results."
        body="PulseLoop monitors curated FR, DACH, and Nordic sources that EU-focused consultants actually need not US-first data repurposed for your market. Continuously, not just when you ask."
        visual={<SignalFeedCard />}
      />
      <FeatureSection
        id="f3"
        tag="The Certificate"
        heading="A methodology section your clients can't question."
        body="Every report ships with an auto-generated Methodology Certificate — sources used, signals collected, confidence thresholds, deduplication method. Attach it. Present it. Never be challenged on your sources again."
        visual={<CertificateCard certCardRef={certCardRef} />}
      />
    </>
  );
}
